apiVersion: v1
kind: Service
metadata:
  name: graphite-statsd
  namespace: graphite
spec:
  type: NodePort
  ports:
    - name: statsd
      port: 8125
      targetPort: 8125
      nodePort: 30000
      protocol: TCP
  selector:
    app.kubernetes.io/name: graphite
    app.kubernetes.io/instance: graphite