apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: chess-engine-api
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/brandonros/hull-wrapper/master/
  chart: hull-wrapper
  targetNamespace: chess-engine-api
  version: 0.2.0
  valuesContent: |-
    hull:
      config:
        general:
          nameOverride: chess-engine-api
          rbac: false
          noObjectNamePrefixes: true
      objects:
        serviceaccount:
          default:
            enabled: false
        deployment:
          chess-engine-api:
            replicas: 2
            annotations:
              linkerd.io/inject: enabled
              config.linkerd.io/proxy-log-level: debug
            pod:
              containers:
                main:
                  resources:
                    requests:
                      memory: 128Mi
                      cpu: 1000m
                    limits:
                      memory: 1024Mi
                      cpu: 1000m
                  image:
                    repository: docker-registry.debian-k3s/chess-engine-api
                    tag: latest
                  env:
                    RUST_LOG:
                      value: debug
                  ports:
                    http:
                      containerPort: 8080
        service:
          chess-engine-api:
            type: ClusterIP
            ports:
              http:
                port: 8080
                targetPort: 8080
