apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: trust-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: trust-manager
  targetNamespace: trust-manager
  version: v0.9.0
  valuesContent: |-
    crds:
      enabled: true
