apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: temporal
  namespace: kube-system
spec:
  repo: https://go.temporal.io/helm-charts
  chart: temporal
  targetNamespace: temporal
  valuesContent: |-
    server:
      replicaCount: 1
      config:
        persistence:
          default:
            driver: sql
            sql:
              driver: postgres12
              host: postgresql.postgresql.svc
              port: 5432
              database: temporal
              user: postgres
              password: postgres123
              maxConns: 20
              maxConnLifetime: "1h"
          visibility:
            driver: sql
            sql:
              driver: postgres12
              host: postgresql.postgresql.svc
              port: 5432
              database: temporal_visibility
              user: postgres
              password: postgres123
              maxConns: 20
              maxConnLifetime: "1h"
    cassandra:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    elasticsearch:
      enabled: false
    cassandra:
      enabled: false
    mysql:
      enabled: false
    schema:
      setup:
        enabled: true
      update:
        enabled: true
