apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
spec:
  sources:
  - secret:
      name: debian-k3s-tls
      key: tls.crt
  target:
    configMap:
      key: ca-bundle.crt
      