apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mlflow
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: mlflow
  targetNamespace: mlflow
  valuesContent: |-
    postgresql:
      enabled: false
    externalDatabase:
      host: postgresql.postgresql.svc.cluster.local
      port: 5432
      database: mlflow
      user: postgres
      password: postgres123
    minio:
      enabled: false
    externalS3:
      host: minio.minio.svc.cluster.local
      accessKeyID: rootuser
      accessKeySecret: rootpass123
