apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: chromium
  namespace: chromium
spec:
  repo: https://raw.githubusercontent.com/brandonros/hull-wrapper/master/
  chart: hull-wrapper
  targetNamespace: chromium
  version: 0.2.0
  valuesContent: |-
    hull:
      config:
        general:
          nameOverride: chromium
          rbac: false
          noObjectNamePrefixes: true
      objects:
        serviceaccount:
          default:
            enabled: false
        deployment:
          chromium:
            replicas: 2
            annotations:
              linkerd.io/inject: enabled
              config.linkerd.io/proxy-log-level: debug
            pod:
              containers:
                main:
                  resources:
                    requests:
                      memory: 128Mi
                      cpu: 1000m
                    limits:
                      memory: 1024Mi
                      cpu: 1000m
                  image:
                    repository: ghcr.io/browserless/chromium
                    tag: v2.24.2
                  env:
                    CONCURRENT:
                      value: 10
                  ports:
                    http:
                      containerPort: 3000
        service:
          chromium:
            type: ClusterIP
            ports:
              http:
                port: 3000
                targetPort: 3000
