apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: windmill
  namespace: kube-system
spec:
  repo: https://windmill-labs.github.io/windmill-helm-charts/
  chart: windmill
  targetNamespace: windmill
  valuesContent: |-
    windmill:
      appReplicas: 1
      lspReplicas: 1
      databaseUrl: postgres://postgres:postgres123@postgresql.postgresql.svc/windmill?sslmode=disable
      workerGroups:
        - name: "default"
          replicas: 1
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: "native"
          replicas: 1
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
          extraEnv:
            - name: "NUM_WORKERS"
              value: "4"
            - name: "SLEEP_QUEUE"
              value: "200"
        - name: "gpu"
          replicas: 0
      app:
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
    postgresql:
      enabled: false