apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ngrok-operator
  namespace: kube-system
spec:
  repo: https://charts.ngrok.com
  chart: ngrok-operator
  targetNamespace: ngrok-operator
  version: 0.16.0-rc.2
  valuesContent: |-
    credentials:
      apiKey: ${NGROK_API_KEY}
      authtoken: ${NGROK_AUTH_TOKEN}
